fixtures:
  repositories:
    apache:
      repo: 'https://github.com/puppetlabs/puppetlabs-apache.git'
      ref:  'origin/master'
  forge_modules:
    stdlib:
      repo: 'puppetlabs-stdlib'
      ref:  '4.2.2'
    concat:
      repo: 'puppetlabs-concat'
      ref:  '1.1.1'
  symlinks:
    shibboleth: "#{source_dir}"
